/**
 * Запуск: npm run test:trade-point-display-labels
 */
import assert from "node:assert/strict";
import {
  computeTradePointAutoDisplayName,
  computeTradePointDisplayName,
  extractStreetAndHouseFromAddress,
  fullscreenCounterpartyLine,
  isLegacyAutoGeneratedTradePointName,
  isManualTradePointName,
  meaningfulTradePointName,
  resolveTradePointDisplayName,
  tradePointManualNameForEdit,
} from "../trade-point-display-labels.js";

assert.equal(meaningfulTradePointName("."), null);
assert.equal(meaningfulTradePointName("  Салон  "), "Салон");

assert.equal(isLegacyAutoGeneratedTradePointName("Торговая точка · Краснодар", "Краснодар"), true);
assert.equal(isLegacyAutoGeneratedTradePointName("Торговая точка 1"), true);
assert.equal(isManualTradePointName("Шахтинский 17", "Шахты"), true);
assert.equal(isManualTradePointName("Торговая точка · Краснодар", "Краснодар"), false);

assert.equal(
  extractStreetAndHouseFromAddress(
    "353460, Краснодарский край, Краснодар г, ул. Дзержинского 195",
    "Краснодар",
  ),
  "ул. Дзержинского 195",
);

assert.equal(
  extractStreetAndHouseFromAddress(
    "353460, Краснодарский край, Геленджик г, А. Блока, дом № 5/15",
    "Геленджик",
  ),
  "А. Блока, № 5/15",
);

const fullCtx = {
  name: "Торговая точка · Краснодар",
  city: "Краснодар",
  address: "353460, Краснодарский край, Краснодар г, ул. Дзержинского 195",
  contactPhone: "+7 900 000-00-00",
  dealerName: "ДВЕРИ 23 ООО",
  dealerId: "client-ma-ma038904",
  tradePointId: "tp-1",
};

assert.equal(
  computeTradePointDisplayName(fullCtx),
  "Краснодар, ул. Дзержинского 195 — +7 900 000-00-00 (ДВЕРИ 23 ООО, #ma-ma038904)",
);

assert.equal(
  computeTradePointDisplayName({
    ...fullCtx,
    name: "Шахтинский 17",
  }),
  "Шахтинский 17",
);

assert.equal(
  computeTradePointDisplayName({
    city: "Краснодар",
    address: "353460, Краснодарский край, Краснодар г, ул. Дзержинского 195",
    dealerName: "ДВЕРИ 23 ООО",
    dealerId: "client-ma-ma038904",
  }),
  "Краснодар, ул. Дзержинского 195 (ДВЕРИ 23 ООО, #ma-ma038904)",
);

assert.equal(
  computeTradePointAutoDisplayName({
    city: "Краснодар",
    address: "ул. Ленина 10",
  }),
  "Краснодар, ул. Ленина 10",
);

assert.equal(tradePointManualNameForEdit("Торговая точка · Москва", "Москва"), "");
assert.equal(tradePointManualNameForEdit("Салон на Арбате", "Москва"), "Салон на Арбате");

assert.equal(
  resolveTradePointDisplayName(
    { name: "ДВЕРИ 23 ООО", id: "client-ma-ma038904" },
    {
      id: "tp-1",
      name: "Торговая точка · Краснодар",
      city: "Краснодар",
      address: "353460, Краснодарский край, Краснодар г, ул. Дзержинского 195",
      contactPhone: "+7 900 000-00-00",
    },
  ),
  "Краснодар, ул. Дзержинского 195 — +7 900 000-00-00 (ДВЕРИ 23 ООО, #ma-ma038904)",
);

assert.equal(
  fullscreenCounterpartyLine(
    { name: "Гервасий Алена Валерьевна ИП" },
    { name: "Октябрьское", releaseCode: "TND-TP-000003", id: "tp-1", city: "Москва" },
  ),
  "Гервасий Алена Валерьевна ИП · ТТ: Октябрьское",
);

console.log("trade-point-display-labels: ok");
