import type { CatalogProduct } from "./catalog-product-type";

/** Демо-модели для связей дилер / ТТ / задачи (без публичного seed). */
export const MOCK_CATALOG_PRODUCTS: CatalogProduct[] = [
  {
    id: "vh-grand-3",
    name: "Гранд 3",
    article: "VH-GRAND-3",
    category: "Входные двери",
    series: "Гранд",
    type: "Модель",
    doorKind: "Входная",
    status: "В продаже",
    image: null,
    shortDescription: "Флагманская входная серия с тёплым контуром и усиленным полотном.",
    description:
      "Серия «Гранд» — представительская линейка входных дверей Tandoor. Многослойное полотно с терморазрывом, четыре контура уплотнения, ригельный замковый комплект. Подходит для квартир и загородных домов с повышенными требованиями к тепло- и шумоизоляции.",
    features: [
      "Терморазрыв и четыре контура уплотнения",
      "Усиленное стальное полотно",
      "Регулируемые петли с противосъёмными штырями",
      "Совместимость с межкомнатными сериями Tandoor по тону",
    ],
    specs: [
      { label: "Толщина полотна, мм", value: "100" },
      { label: "Размер полотна, мм", value: "2050 × 860 / 960" },
      { label: "Покрытие", value: "МДФ-панель + Soft-touch" },
      { label: "Замки", value: "Сувальдный + цилиндровый" },
      { label: "Глазок", value: "Широкоугольный" },
      { label: "Утеплитель", value: "Минеральный" },
    ],
    equipment: [
      "Стальная коробка",
      "Полотно",
      "Петли усиленные, 3 шт.",
      "Замковый комплект (без цилиндра)",
      "Глазок широкоугольный",
      "Ручка на выбор",
    ],
    variants: [
      { label: "Открывание", value: "На себя / От себя" },
      { label: "Сторона петель", value: "Левая / Правая" },
      { label: "Внешняя отделка", value: "Антрацит / Венге / Дуб" },
    ],
    colors: ["Антрацит", "Венге", "Дуб натуральный"],
    sizes: ["860 × 2050", "960 × 2050"],
    manufacturer: "Tandoor",
    warranty: "5 лет",
    coating: "МДФ-панель + Soft-touch",
    openType: "На себя / От себя",
    isTop: true,
    isNew: false,
    isExclusive: false,
    isAction: false,
    inStock: true,
    showcasePriority: 10,
    salesPriority: 10,
    recommendedForShowcase: true,
    relatedDealerIds: ["001", "002", "007", "012", "015"],
    relatedTradePointIds: ["001-01", "007-01", "012-01"],
    relatedTaskCount: 2,
    history: [
      { date: "12.04.2026", event: "Обновлены фотоматериалы для каталога дилеров" },
      { date: "03.03.2026", event: "Добавлено исполнение в цвете «Дуб натуральный»" },
      { date: "20.01.2026", event: "Согласована витринная выкладка для регионов" },
    ],
  },
  {
    id: "vh-grand-4",
    name: "Гранд 4",
    article: "VH-GRAND-4",
    category: "Входные двери",
    series: "Гранд",
    type: "Модель",
    doorKind: "Входная",
    status: "В продаже",
    image: null,
    shortDescription: "Облегчённая комплектация серии «Гранд» с базовой фурнитурой.",
    description:
      "Та же геометрия и термоконтур, что у флагмана, но в более лаконичном исполнении: один сувальдный замок и базовый набор петель. Подходит для типовых квартир.",
    features: [
      "Базовая фурнитура серии «Гранд»",
      "Терморазрыв",
      "Совместимость с МК-сериями по фактуре",
    ],
    specs: [
      { label: "Толщина полотна, мм", value: "90" },
      { label: "Размер полотна, мм", value: "2050 × 860 / 960" },
      { label: "Покрытие", value: "МДФ-панель" },
      { label: "Замки", value: "Сувальдный" },
      { label: "Глазок", value: "Стандартный" },
    ],
    equipment: ["Коробка", "Полотно", "Петли 3 шт.", "Замковый комплект", "Глазок", "Ручка на выбор"],
    variants: [
      { label: "Открывание", value: "На себя / От себя" },
      { label: "Сторона петель", value: "Левая / Правая" },
    ],
    colors: ["Антрацит", "Венге"],
    sizes: ["860 × 2050", "960 × 2050"],
    manufacturer: "Tandoor",
    warranty: "3 года",
    coating: "МДФ-панель",
    openType: "На себя / От себя",
    isTop: true,
    isNew: false,
    isExclusive: false,
    isAction: false,
    inStock: true,
    showcasePriority: 8,
    salesPriority: 9,
    recommendedForShowcase: true,
    relatedDealerIds: ["001", "003", "007"],
    relatedTradePointIds: ["001-01", "001-02"],
    relatedTaskCount: 0,
    history: [
      { date: "10.04.2026", event: "Обновлены технические характеристики" },
      { date: "18.02.2026", event: "Добавлена в основной выставочный набор" },
    ],
  },
  {
    id: "vh-grand-5",
    name: "Гранд 5",
    article: "VH-GRAND-5",
    category: "Входные двери",
    series: "Гранд",
    type: "Модель",
    doorKind: "Входная",
    status: "В продаже",
    image: null,
    shortDescription: "Расширенная комплектация серии «Гранд» с дополнительным контуром.",
    description:
      "Версия с пятью контурами уплотнения и усиленным замковым узлом. Рекомендуется для домов и коттеджей.",
    features: ["Пять контуров уплотнения", "Усиленный замковый узел", "Бронепластина"],
    specs: [
      { label: "Толщина полотна, мм", value: "100" },
      { label: "Размер полотна, мм", value: "2050 × 960" },
      { label: "Покрытие", value: "МДФ + Soft-touch" },
      { label: "Замки", value: "Сувальдный + цилиндровый, броненакладка" },
    ],
    equipment: ["Коробка", "Полотно", "Петли 3 шт.", "Замковый комплект", "Бронепластина", "Глазок"],
    variants: [
      { label: "Открывание", value: "На себя / От себя" },
      { label: "Сторона петель", value: "Левая / Правая" },
      { label: "Внешняя отделка", value: "Антрацит / Венге / Дуб / Графит" },
    ],
    colors: ["Антрацит", "Венге", "Дуб натуральный", "Графит"],
    sizes: ["960 × 2050"],
    manufacturer: "Tandoor",
    warranty: "5 лет",
    coating: "МДФ + Soft-touch",
    openType: "На себя / От себя",
    isTop: true,
    isNew: true,
    isExclusive: true,
    isAction: false,
    inStock: true,
    showcasePriority: 10,
    salesPriority: 10,
    recommendedForShowcase: true,
    relatedDealerIds: ["001", "002", "004", "007", "010", "018"],
    relatedTradePointIds: ["001-01", "007-01", "010-01", "018-01"],
    relatedTaskCount: 3,
    history: [
      { date: "28.04.2026", event: "Поставлена в эксклюзивную программу для розничных партнёров" },
      { date: "15.03.2026", event: "Получены сертификаты по новой комплектации" },
      { date: "21.02.2026", event: "Запуск серии в основную линейку" },
    ],
  },
  {
    id: "vh-kvarc",
    name: "Кварц",
    article: "VH-KVARC",
    category: "Входные двери",
    series: "Кварц",
    type: "Модель",
    doorKind: "Входная",
    status: "В продаже",
    image: null,
    shortDescription: "Стальная входная дверь среднего сегмента с лаконичной геометрией.",
    description:
      "Серия «Кварц» — практичный выбор для квартир. Стальное полотно, два контура уплотнения, базовый замковый комплект.",
    features: ["Стальное полотно", "Два контура уплотнения", "Регулируемые петли"],
    specs: [
      { label: "Толщина полотна, мм", value: "70" },
      { label: "Размер полотна, мм", value: "2050 × 860" },
      { label: "Покрытие", value: "МДФ-панель" },
      { label: "Замки", value: "Сувальдный" },
    ],
    equipment: ["Коробка", "Полотно", "Петли 2 шт.", "Замковый комплект", "Глазок"],
    variants: [
      { label: "Открывание", value: "На себя / От себя" },
      { label: "Сторона петель", value: "Левая / Правая" },
    ],
    colors: ["Антрацит", "Белый"],
    sizes: ["860 × 2050"],
    manufacturer: "Tandoor",
    warranty: "2 года",
    coating: "МДФ-панель",
    openType: "На себя / От себя",
    isTop: false,
    isNew: false,
    isExclusive: false,
    isAction: true,
    inStock: true,
    showcasePriority: 6,
    salesPriority: 8,
    recommendedForShowcase: true,
    relatedDealerIds: ["005", "007", "014"],
    relatedTradePointIds: ["007-01", "014-01"],
    relatedTaskCount: 1,
    history: [
      { date: "01.04.2026", event: "Включена в текущую акцию для дилеров" },
      { date: "10.01.2026", event: "Корректировка комплектации (петли)" },
    ],
  },
  {
    id: "vh-siriys",
    name: "Сириус",
    article: "VH-SIRIYS",
    category: "Входные двери",
    series: "Сириус",
    type: "Модель",
    doorKind: "Входная",
    status: "К заказу",
    image: null,
    shortDescription: "Серия с акцентом на дизайн фасада и индивидуальные исполнения.",
    description:
      "«Сириус» собирается под заказ с индивидуальным фасадом. Для розничной витрины используется как образец возможностей серии.",
    features: ["Дизайнерский фасад", "Под заказ", "Совмещается с МДФ-панелями"],
    specs: [
      { label: "Толщина полотна, мм", value: "90" },
      { label: "Размер полотна, мм", value: "по проекту" },
      { label: "Покрытие", value: "Эмаль / МДФ" },
    ],
    equipment: ["Коробка", "Полотно", "Петли 3 шт.", "Замковый комплект", "Глазок"],
    variants: [
      { label: "Открывание", value: "На себя / От себя" },
      { label: "Сторона петель", value: "Левая / Правая" },
      { label: "Фасад", value: "По проекту партнёра" },
    ],
    colors: ["Антрацит", "Графит", "По проекту"],
    sizes: ["По проекту"],
    manufacturer: "Tandoor",
    warranty: "3 года",
    coating: "Эмаль / МДФ",
    openType: "На себя / От себя",
    isTop: false,
    isNew: true,
    isExclusive: true,
    isAction: false,
    inStock: false,
    showcasePriority: 7,
    salesPriority: 7,
    recommendedForShowcase: false,
    relatedDealerIds: ["007", "011", "020"],
    relatedTradePointIds: ["007-01", "011-01"],
    relatedTaskCount: 2,
    history: [
      { date: "20.04.2026", event: "Подготовка эксклюзивных макетов для региональной выставки" },
      { date: "05.03.2026", event: "Расширение опций индивидуального фасада" },
    ],
  },
  {
    id: "vh-neapol",
    name: "Неаполь",
    article: "VH-NEAPOL",
    category: "Входные двери",
    series: "Неаполь",
    type: "Модель",
    doorKind: "Входная",
    status: "В продаже",
    image: null,
    shortDescription: "Классика серии входных дверей с фактурными МДФ-панелями.",
    description:
      "Серия «Неаполь» сочетает классические молдинги и современную фурнитуру. Один из устойчивых лидеров продаж.",
    features: ["Фактурные МДФ-панели", "Усиленный замковый узел", "Стабильный спрос"],
    specs: [
      { label: "Толщина полотна, мм", value: "90" },
      { label: "Размер полотна, мм", value: "2050 × 860 / 960" },
      { label: "Покрытие", value: "МДФ-панель" },
      { label: "Замки", value: "Сувальдный + цилиндровый" },
    ],
    equipment: ["Коробка", "Полотно", "Петли 3 шт.", "Замковый комплект", "Глазок"],
    variants: [
      { label: "Открывание", value: "На себя / От себя" },
      { label: "Сторона петель", value: "Левая / Правая" },
      { label: "Внешняя отделка", value: "Венге / Дуб / Орех" },
    ],
    colors: ["Венге", "Дуб натуральный", "Орех"],
    sizes: ["860 × 2050", "960 × 2050"],
    manufacturer: "Tandoor",
    warranty: "3 года",
    coating: "МДФ-панель",
    openType: "На себя / От себя",
    isTop: true,
    isNew: false,
    isExclusive: false,
    isAction: false,
    inStock: true,
    showcasePriority: 9,
    salesPriority: 10,
    recommendedForShowcase: true,
    relatedDealerIds: ["001", "002", "003", "005", "006"],
    relatedTradePointIds: ["001-01", "003-01", "006-01"],
    relatedTaskCount: 0,
    history: [
      { date: "08.04.2026", event: "Обновлена продуктовая презентация для розничных дилеров" },
      { date: "16.02.2026", event: "Добавлено исполнение в цвете «Орех»" },
    ],
  },
  {
    id: "vh-kapelli",
    name: "Капелли",
    article: "VH-KAPELLI",
    category: "Входные двери",
    series: "Капелли",
    type: "Модель",
    doorKind: "Входная",
    status: "Ограниченный запас",
    image: null,
    shortDescription: "Серия с нестандартной геометрией фасада, ограниченные партии.",
    description:
      "«Капелли» — позиция с ограниченным наличием. Перед выкладкой на витрину уточняйте остаток у регионального менеджера.",
    features: ["Нестандартный фасад", "Ограниченные партии"],
    specs: [
      { label: "Толщина полотна, мм", value: "90" },
      { label: "Размер полотна, мм", value: "2050 × 860" },
      { label: "Покрытие", value: "МДФ-панель" },
    ],
    equipment: ["Коробка", "Полотно", "Петли 3 шт.", "Замковый комплект"],
    variants: [
      { label: "Открывание", value: "На себя / От себя" },
      { label: "Сторона петель", value: "Левая / Правая" },
    ],
    colors: ["Антрацит"],
    sizes: ["860 × 2050"],
    manufacturer: "Tandoor",
    warranty: "3 года",
    coating: "МДФ-панель",
    openType: "На себя / От себя",
    isTop: false,
    isNew: false,
    isExclusive: false,
    isAction: false,
    inStock: false,
    showcasePriority: 4,
    salesPriority: 5,
    recommendedForShowcase: false,
    relatedDealerIds: ["007", "013", "022"],
    relatedTradePointIds: ["007-02", "013-01"],
    relatedTaskCount: 5,
    history: [
      { date: "30.04.2026", event: "Согласование графика поставок ограниченной партии" },
      { date: "12.03.2026", event: "Уточнение комплектации с производством" },
    ],
  },
  {
    id: "mk-grand-3-mk",
    name: "Гранд 3 МК",
    article: "MK-GRAND-3",
    category: "Межкомнатные двери",
    series: "Гранд",
    type: "Модель",
    doorKind: "Межкомнатная",
    status: "В продаже",
    image: null,
    shortDescription: "Межкомнатная серия в едином стиле с входной серией «Гранд».",
    description:
      "МК-серия «Гранд 3» сделана в одинаковой фактуре с входной серией. Используется в составе комплектов «вход + межкомнатные» для единого стиля квартиры.",
    features: ["Совместимость с входной серией «Гранд»", "Скрытые петли", "Единая фактура полотна"],
    specs: [
      { label: "Толщина полотна, мм", value: "40" },
      { label: "Размер полотна, мм", value: "2000 × 600 / 700 / 800 / 900" },
      { label: "Покрытие", value: "МДФ-панель" },
      { label: "Тип короба", value: "Стандартный" },
    ],
    equipment: ["Полотно", "Коробка", "Наличники", "Петли скрытые", "Замок-защёлка"],
    variants: [
      { label: "Сторона петель", value: "Левая / Правая" },
      { label: "Цвет покрытия", value: "Венге / Дуб / Антрацит" },
      { label: "Стекло", value: "Без стекла / Матовое" },
    ],
    colors: ["Венге", "Дуб натуральный", "Антрацит"],
    sizes: ["600 × 2000", "700 × 2000", "800 × 2000", "900 × 2000"],
    manufacturer: "Tandoor",
    warranty: "3 года",
    coating: "МДФ-панель",
    openType: "Распашная",
    isTop: true,
    isNew: false,
    isExclusive: false,
    isAction: false,
    inStock: true,
    showcasePriority: 9,
    salesPriority: 9,
    recommendedForShowcase: true,
    relatedDealerIds: ["001", "008", "012"],
    relatedTradePointIds: ["001-02", "012-01"],
    relatedTaskCount: 0,
    history: [
      { date: "03.04.2026", event: "Обновлена линейка размеров полотна" },
    ],
  },
  {
    id: "mk-grand-4",
    name: "Гранд 4 МК",
    article: "MK-GRAND-4",
    category: "Межкомнатные двери",
    series: "Гранд",
    type: "Модель",
    doorKind: "Межкомнатная",
    status: "В продаже",
    image: null,
    shortDescription: "Облегчённая межкомнатная модель серии «Гранд» с базовой фурнитурой.",
    description:
      "Базовая комплектация межкомнатной серии «Гранд». Подходит для типовых проёмов и быстрых заказов.",
    features: ["Базовый комплект", "Совместимость с входной серией"],
    specs: [
      { label: "Толщина полотна, мм", value: "40" },
      { label: "Размер полотна, мм", value: "2000 × 600 / 700 / 800" },
      { label: "Покрытие", value: "МДФ-панель" },
    ],
    equipment: ["Полотно", "Коробка", "Наличники", "Петли", "Замок-защёлка"],
    variants: [
      { label: "Сторона петель", value: "Левая / Правая" },
      { label: "Цвет покрытия", value: "Венге / Дуб / Серый" },
    ],
    colors: ["Венге", "Дуб натуральный", "Серый"],
    sizes: ["600 × 2000", "700 × 2000", "800 × 2000"],
    manufacturer: "Tandoor",
    warranty: "2 года",
    coating: "МДФ-панель",
    openType: "Распашная",
    isTop: false,
    isNew: false,
    isExclusive: false,
    isAction: false,
    inStock: true,
    showcasePriority: 6,
    salesPriority: 7,
    recommendedForShowcase: false,
    relatedDealerIds: ["004", "009"],
    relatedTradePointIds: ["004-01"],
    relatedTaskCount: 4,
    history: [
      { date: "21.04.2026", event: "Обновлены наличники и крепёжный комплект" },
    ],
  },
  {
    id: "mk-grand-5",
    name: "Гранд 5 МК",
    article: "MK-GRAND-5",
    category: "Межкомнатные двери",
    series: "Гранд",
    type: "Модель",
    doorKind: "Межкомнатная",
    status: "В продаже",
    image: null,
    shortDescription: "Расширенная межкомнатная серия «Гранд» со скрытыми петлями.",
    description:
      "Версия с улучшенной фурнитурой и скрытыми петлями. Рекомендуется к выкладке в основной зоне витрины.",
    features: ["Скрытые петли", "Магнитный замок-защёлка", "Совместимость с входной серией"],
    specs: [
      { label: "Толщина полотна, мм", value: "44" },
      { label: "Размер полотна, мм", value: "2000 × 700 / 800 / 900" },
      { label: "Покрытие", value: "МДФ + Soft-touch" },
    ],
    equipment: ["Полотно", "Коробка", "Наличники", "Петли скрытые", "Замок магнитный"],
    variants: [
      { label: "Сторона петель", value: "Левая / Правая" },
      { label: "Цвет покрытия", value: "Венге / Дуб / Антрацит / Графит" },
      { label: "Стекло", value: "Без стекла / Матовое / С рисунком" },
    ],
    colors: ["Венге", "Дуб натуральный", "Антрацит", "Графит"],
    sizes: ["700 × 2000", "800 × 2000", "900 × 2000"],
    manufacturer: "Tandoor",
    warranty: "3 года",
    coating: "МДФ + Soft-touch",
    openType: "Распашная",
    isTop: true,
    isNew: true,
    isExclusive: false,
    isAction: false,
    inStock: true,
    showcasePriority: 8,
    salesPriority: 9,
    recommendedForShowcase: true,
    relatedDealerIds: ["001", "002", "003", "005", "006"],
    relatedTradePointIds: ["001-01", "003-01", "006-01"],
    relatedTaskCount: 0,
    history: [
      { date: "26.04.2026", event: "Старт выкладки в основной зоне витрины у партнёров" },
      { date: "05.03.2026", event: "Введены два новых исполнения цвета" },
    ],
  },
  {
    id: "mk-kapelli",
    name: "Капелли МК",
    article: "MK-KAPELLI",
    category: "Межкомнатные двери",
    series: "Капелли",
    type: "Модель",
    doorKind: "Межкомнатная",
    status: "В продаже",
    image: null,
    shortDescription: "Тонкая межкомнатная модель с акцентом на дизайн.",
    description:
      "Лёгкое полотно и узкая коробка для современных интерьеров. Хорошо смотрится в комплектации с серией «Капелли» по входной двери.",
    features: ["Узкая коробка", "Лаконичный дизайн", "Совместимость с входной серией «Капелли»"],
    specs: [
      { label: "Толщина полотна, мм", value: "40" },
      { label: "Размер полотна, мм", value: "2000 × 600 / 700 / 800" },
      { label: "Покрытие", value: "Эмаль" },
    ],
    equipment: ["Полотно", "Коробка узкая", "Наличники", "Петли скрытые", "Замок-защёлка"],
    variants: [
      { label: "Сторона петель", value: "Левая / Правая" },
      { label: "Цвет покрытия", value: "Белый / Антрацит / Графит" },
    ],
    colors: ["Белый", "Антрацит", "Графит"],
    sizes: ["600 × 2000", "700 × 2000", "800 × 2000"],
    manufacturer: "Tandoor",
    warranty: "2 года",
    coating: "Эмаль",
    openType: "Распашная",
    isTop: false,
    isNew: true,
    isExclusive: false,
    isAction: true,
    inStock: true,
    showcasePriority: 7,
    salesPriority: 8,
    recommendedForShowcase: true,
    relatedDealerIds: ["001", "019"],
    relatedTradePointIds: ["001-01"],
    relatedTaskCount: 1,
    history: [
      { date: "15.04.2026", event: "Включена в текущую акцию для дилерской сети" },
    ],
  },
  {
    id: "sk-line",
    name: "Скрытая дверь «Линия»",
    article: "SK-LINE",
    category: "Скрытые двери",
    series: "Линия",
    type: "Модель",
    doorKind: "Скрытая",
    status: "В продаже",
    image: null,
    shortDescription: "Скрытая дверь со скрытой коробкой и плоским полотном под покраску.",
    description:
      "Полотно «в уровень» со стеной и алюминиевая скрытая коробка. Подходит для проектов с акцентом на минимализм.",
    features: ["Скрытая коробка", "Полотно под покраску", "Магнитный замок"],
    specs: [
      { label: "Толщина полотна, мм", value: "40" },
      { label: "Размер полотна, мм", value: "2000 × 700 / 800" },
      { label: "Покрытие", value: "Грунт под покраску" },
    ],
    equipment: ["Полотно", "Коробка алюминиевая скрытая", "Петли скрытые", "Замок магнитный"],
    variants: [
      { label: "Сторона петель", value: "Левая / Правая" },
      { label: "Открывание", value: "В сторону комнаты / В сторону коридора" },
    ],
    colors: ["Под покраску"],
    sizes: ["700 × 2000", "800 × 2000"],
    manufacturer: "Tandoor",
    warranty: "3 года",
    coating: "Грунт под покраску",
    openType: "Распашная скрытая",
    isTop: false,
    isNew: true,
    isExclusive: false,
    isAction: false,
    inStock: true,
    showcasePriority: 6,
    salesPriority: 7,
    recommendedForShowcase: true,
    relatedDealerIds: ["010", "016", "018"],
    relatedTradePointIds: ["010-01", "018-01"],
    relatedTaskCount: 1,
    history: [
      { date: "22.04.2026", event: "Подготовлена техническая карта для проектов под покраску" },
    ],
  },
  {
    id: "ns-project-l",
    name: "Нестандарт «Проект» L",
    article: "NS-PROJECT-L",
    category: "Двери для нестандартных проёмов",
    series: "Проект",
    type: "Модель",
    doorKind: "Входная",
    status: "Под заказ",
    image: null,
    shortDescription: "Модель под индивидуальный проект и нестандартные проёмы.",
    description:
      "Изготовление по проекту партнёра: высота до 2400 мм, ширина — по замеру. Используется в B2B-поставках в офисные центры и нестандартные квартиры.",
    features: ["Высота до 2400 мм", "Ширина по замеру", "Усиленные петли"],
    specs: [
      { label: "Высота, мм", value: "до 2400" },
      { label: "Ширина, мм", value: "по проекту" },
      { label: "Покрытие", value: "По проекту" },
    ],
    equipment: ["Коробка", "Полотно", "Петли 4 шт.", "Замок врезной"],
    variants: [
      { label: "Открывание", value: "На себя / От себя" },
      { label: "Сторона петель", value: "Левая / Правая" },
      { label: "Фасад", value: "По проекту партнёра" },
    ],
    colors: ["По проекту"],
    sizes: ["По проекту"],
    manufacturer: "Tandoor",
    warranty: "3 года",
    coating: "По проекту",
    openType: "На себя / От себя",
    isTop: false,
    isNew: false,
    isExclusive: true,
    isAction: false,
    inStock: false,
    showcasePriority: 3,
    salesPriority: 6,
    recommendedForShowcase: false,
    relatedDealerIds: ["006", "014"],
    relatedTradePointIds: ["014-01"],
    relatedTaskCount: 0,
    history: [
      { date: "11.04.2026", event: "Согласование с производством типовых нестандартных размеров" },
    ],
  },
];
