/* eslint-disable */
/**
 * Автогенерация: node scripts/import-tandoor-public-catalog.mjs
 * Публичные данные tandoor.ru; изображения — локальные WebP в /catalog-real/
 */

export type TandoorRealCatalogSeedItem = {
  id: string;
  sourceUrl: string;
  title: string;
  category: "entrance" | "interior" | "hardware";
  categoryLabel: string;
  collection?: string;
  finish?: string;
  priceRetail?: number;
  pricePromo?: number;
  imageSrc: string;
  imageAlt: string;
  shortDescription?: string;
  tags: string[];
  searchText: string;
};

export const TANDOOR_REAL_CATALOG_SEED: TandoorRealCatalogSeedItem[] = [
  {
    "id": "tc-vh-era-grafit-belyy-matovyy-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/era-grafit-belyy-matovyy-860kh2050-levaya/",
    "title": "Эра Графит / Белый матовый 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Эра",
    "priceRetail": 40310,
    "imageSrc": "/catalog-real/tc-vh-era-grafit-belyy-matovyy-860kh2050-levaya.webp",
    "imageAlt": "Эра Графит / Белый матовый 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Эра 860x2050 в Краснодаре по доступной цене 40&nbsp;310 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Эра",
      "Графит",
      "Белый",
      "матовый",
      "860х2050",
      "левая",
      "входные",
      "ВХ",
      "входная",
      "МДФ",
      "белый матовый",
      "графит"
    ],
    "searchText": "эра графит / белый матовый 860х2050 левая входные двери эра графит белый матовый 860х2050 левая входные вх входная мдф белый матовый графит"
  },
  {
    "id": "tc-mk-sk-2-belyy-matovyy-pet-dg-2000-800-90p",
    "sourceUrl": "https://tandoor.ru/catalog/product/sk-2-belyy-matovyy-pet-dg-2000-800-90p/",
    "title": "СК-2 белый матовый ПЭТ ДГ 2000*800 (90П)",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "СК-2",
    "priceRetail": 6810,
    "imageSrc": "/catalog-real/tc-mk-sk-2-belyy-matovyy-pet-dg-2000-800-90p.webp",
    "imageAlt": "СК-2 белый матовый ПЭТ ДГ 2000*800 (90П)",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери СК-2 2000х800 в Краснодаре по доступной цене 6&nbsp;810 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "СК-2",
      "белый",
      "матовый",
      "ПЭТ",
      "2000*800",
      "(90П)",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "ск-2 белый матовый пэт дг 2000*800 (90п) межкомнатные двери ск-2 белый матовый пэт 2000*800 (90п) межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-vh-standart-bukle-grafit-velutto-bianco-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/standart-bukle-grafit-velutto-bianco-860kh2050-levaya/",
    "title": "Стандарт Букле графит / Velutto Bianco 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Стандарт",
    "priceRetail": 21810,
    "imageSrc": "/catalog-real/tc-vh-standart-bukle-grafit-velutto-bianco-860kh2050-levaya.webp",
    "imageAlt": "Стандарт Букле графит / Velutto Bianco 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Стандарт 860x2050 в Краснодаре по доступной цене 21&nbsp;810 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Стандарт",
      "Букле",
      "графит",
      "Velutto",
      "Bianco",
      "860х2050",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "стандарт букле графит / velutto bianco 860х2050 левая входные двери стандарт букле графит velutto bianco 860х2050 входные вх входная"
  },
  {
    "id": "tc-vh-panteon-bukle-temno-seryy-chernyy-kvarts-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/panteon-bukle-temno-seryy-chernyy-kvarts-860kh2050-levaya/",
    "title": "Пантеон Букле темно-серый / Черный кварц 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Пантеон",
    "priceRetail": 30460,
    "imageSrc": "/catalog-real/tc-vh-panteon-bukle-temno-seryy-chernyy-kvarts-860kh2050-levaya.webp",
    "imageAlt": "Пантеон Букле темно-серый / Черный кварц 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Пантеон 860x2050 в Краснодаре по доступной цене 30&nbsp;460 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Пантеон",
      "Букле",
      "темно-серый",
      "Черный",
      "кварц",
      "860х2050",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "пантеон букле темно-серый / черный кварц 860х2050 левая входные двери пантеон букле темно-серый черный кварц 860х2050 входные вх входная"
  },
  {
    "id": "tc-vh-panteon-bukle-temno-seryy-belyy-sneg-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/panteon-bukle-temno-seryy-belyy-sneg-860kh2050-levaya/",
    "title": "Пантеон Букле темно-серый / Белый снег 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Пантеон",
    "priceRetail": 29010,
    "imageSrc": "/catalog-real/tc-vh-panteon-bukle-temno-seryy-belyy-sneg-860kh2050-levaya.webp",
    "imageAlt": "Пантеон Букле темно-серый / Белый снег 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Пантеон 860x2050 в Краснодаре по доступной цене 29&nbsp;010 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Пантеон",
      "Букле",
      "темно-серый",
      "Белый",
      "снег",
      "860х2050",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "пантеон букле темно-серый / белый снег 860х2050 левая входные двери пантеон букле темно-серый белый снег 860х2050 входные вх входная"
  },
  {
    "id": "tc-vh-midas-orekh-pekan-shokolad-emalit-belyy-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/midas-orekh-pekan-shokolad-emalit-belyy-860kh2050-levaya/",
    "title": "Мидас Орех пекан шоколад / Эмалит белый 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Мидас",
    "priceRetail": 45310,
    "imageSrc": "/catalog-real/tc-vh-midas-orekh-pekan-shokolad-emalit-belyy-860kh2050-levaya.webp",
    "imageAlt": "Мидас Орех пекан шоколад / Эмалит белый 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Мидас 860x2050 в Краснодаре по доступной цене 45&nbsp;310 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Мидас",
      "Орех",
      "пекан",
      "шоколад",
      "Эмалит",
      "белый",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "мидас орех пекан шоколад / эмалит белый 860х2050 левая входные двери мидас орех пекан шоколад эмалит белый входные вх входная"
  },
  {
    "id": "tc-vh-panteon-termo-bukle-temno-seryy-mramor-temnyy-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/panteon-termo-bukle-temno-seryy-mramor-temnyy-860kh2050-levaya/",
    "title": "Пантеон термо Букле темно-серый / Мрамор темный 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Пантеон",
    "priceRetail": 34810,
    "imageSrc": "/catalog-real/tc-vh-panteon-termo-bukle-temno-seryy-mramor-temnyy-860kh2050-levaya.webp",
    "imageAlt": "Пантеон термо Букле темно-серый / Мрамор темный 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Пантеон термо 860x2050 в Краснодаре по доступной цене 34&nbsp;810 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Пантеон",
      "термо",
      "Букле",
      "темно-серый",
      "Мрамор",
      "темный",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "пантеон термо букле темно-серый / мрамор темный 860х2050 левая входные двери пантеон термо букле темно-серый мрамор темный входные вх входная"
  },
  {
    "id": "tc-vh-ultra-pikhtovyy-emalit-belyy-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/ultra-pikhtovyy-emalit-belyy-860kh2050-levaya/",
    "title": "Ультра Пихтовый / Эмалит белый 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Ультра",
    "priceRetail": 46810,
    "imageSrc": "/catalog-real/tc-vh-ultra-pikhtovyy-emalit-belyy-860kh2050-levaya.webp",
    "imageAlt": "Ультра Пихтовый / Эмалит белый 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Ультра 860x2050 в Краснодаре по доступной цене 46&nbsp;810 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Ультра",
      "Пихтовый",
      "Эмалит",
      "белый",
      "860х2050",
      "левая",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "ультра пихтовый / эмалит белый 860х2050 левая входные двери ультра пихтовый эмалит белый 860х2050 левая входные вх входная"
  },
  {
    "id": "tc-vh-panteon-termo-bukle-temno-seryy-temno-seryy-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/panteon-termo-bukle-temno-seryy-temno-seryy-860kh2050-levaya/",
    "title": "Пантеон термо Букле темно-серый / Темно-серый 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Пантеон",
    "priceRetail": 36260,
    "imageSrc": "/catalog-real/tc-vh-panteon-termo-bukle-temno-seryy-temno-seryy-860kh2050-levaya.webp",
    "imageAlt": "Пантеон термо Букле темно-серый / Темно-серый 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Пантеон термо 860x2050 в Краснодаре по доступной цене 36&nbsp;260 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Пантеон",
      "термо",
      "Букле",
      "темно-серый",
      "Темно-серый",
      "860х2050",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "пантеон термо букле темно-серый / темно-серый 860х2050 левая входные двери пантеон термо букле темно-серый темно-серый 860х2050 входные вх входная"
  },
  {
    "id": "tc-vh-pandora-dub-korichnevyy-belyy-mat-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/pandora-dub-korichnevyy-belyy-mat-860kh2050-levaya/",
    "title": "Пандора Дуб коричневый / Белый мат 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Пандора",
    "priceRetail": 37310,
    "imageSrc": "/catalog-real/tc-vh-pandora-dub-korichnevyy-belyy-mat-860kh2050-levaya.webp",
    "imageAlt": "Пандора Дуб коричневый / Белый мат 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Пандора 860x2050 в Краснодаре по доступной цене 37&nbsp;310 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Пандора",
      "Дуб",
      "коричневый",
      "Белый",
      "мат",
      "860х2050",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "пандора дуб коричневый / белый мат 860х2050 левая входные двери пандора дуб коричневый белый мат 860х2050 входные вх входная"
  },
  {
    "id": "tc-vh-apart-grafit-rustik-seryy-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/apart-grafit-rustik-seryy-860kh2050-levaya/",
    "title": "Апарт Графит / Рустик серый 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Апарт",
    "priceRetail": 31510,
    "imageSrc": "/catalog-real/tc-vh-apart-grafit-rustik-seryy-860kh2050-levaya.webp",
    "imageAlt": "Апарт Графит / Рустик серый 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Апарт 860x2050 в Краснодаре по доступной цене 31&nbsp;510 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Апарт",
      "Графит",
      "Рустик",
      "серый",
      "860х2050",
      "левая",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "апарт графит / рустик серый 860х2050 левая входные двери апарт графит рустик серый 860х2050 левая входные вх входная"
  },
  {
    "id": "tc-vh-amulet-grafit-seryy-belyy-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/amulet-grafit-seryy-belyy-860kh2050-levaya/",
    "title": "Амулет Графит серый / Белый 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Амулет",
    "priceRetail": 30610,
    "imageSrc": "/catalog-real/tc-vh-amulet-grafit-seryy-belyy-860kh2050-levaya.webp",
    "imageAlt": "Амулет Графит серый / Белый 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Амулет 860x2050 в Краснодаре по доступной цене 30&nbsp;610 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Амулет",
      "Графит",
      "серый",
      "Белый",
      "860х2050",
      "левая",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "амулет графит серый / белый 860х2050 левая входные двери амулет графит серый белый 860х2050 левая входные вх входная"
  },
  {
    "id": "tc-vh-standart-antik-mednyy-shokolad-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/standart-antik-mednyy-shokolad-860kh2050-levaya/",
    "title": "Стандарт Антик медный / Шоколад 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Стандарт",
    "priceRetail": 21810,
    "imageSrc": "/catalog-real/tc-vh-standart-antik-mednyy-shokolad-860kh2050-levaya.webp",
    "imageAlt": "Стандарт Антик медный / Шоколад 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Стандарт 860x2050 в Краснодаре по доступной цене 21&nbsp;810 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Стандарт",
      "Антик",
      "медный",
      "Шоколад",
      "860х2050",
      "левая",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "стандарт антик медный / шоколад 860х2050 левая входные двери стандарт антик медный шоколад 860х2050 левая входные вх входная"
  },
  {
    "id": "tc-vh-layt-bukle-grafit-kanadskiy-dub-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/layt-bukle-grafit-kanadskiy-dub-860kh2050-levaya/",
    "title": "Лайт Букле графит / Канадский дуб 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Лайт",
    "priceRetail": 19310,
    "imageSrc": "/catalog-real/tc-vh-layt-bukle-grafit-kanadskiy-dub-860kh2050-levaya.webp",
    "imageAlt": "Лайт Букле графит / Канадский дуб 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Лайт 860x2050 в Краснодаре по доступной цене 19&nbsp;310 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Лайт",
      "Букле",
      "графит",
      "Канадский",
      "дуб",
      "860х2050",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "лайт букле графит / канадский дуб 860х2050 левая входные двери лайт букле графит канадский дуб 860х2050 входные вх входная"
  },
  {
    "id": "tc-vh-layt-antik-mednyy-larche-shokolad-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/layt-antik-mednyy-larche-shokolad-860kh2050-levaya/",
    "title": "Лайт Антик медный / Ларче шоколад 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Лайт",
    "priceRetail": 19310,
    "imageSrc": "/catalog-real/tc-vh-layt-antik-mednyy-larche-shokolad-860kh2050-levaya.webp",
    "imageAlt": "Лайт Антик медный / Ларче шоколад 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Лайт 860x2050 в Краснодаре по доступной цене 19&nbsp;310 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Лайт",
      "Антик",
      "медный",
      "Ларче",
      "шоколад",
      "860х2050",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "лайт антик медный / ларче шоколад 860х2050 левая входные двери лайт антик медный ларче шоколад 860х2050 входные вх входная"
  },
  {
    "id": "tc-vh-stounvud-skol-kamnya-blek-orekh-noche-tertona-850kh2030-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/stounvud-skol-kamnya-blek-orekh-noche-tertona-850kh2030-levaya/",
    "title": "Стоунвуд Скол камня блэк / Орех ноче тертона 850х2030 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Стоунвуд",
    "priceRetail": 57610,
    "imageSrc": "/catalog-real/tc-vh-stounvud-skol-kamnya-blek-orekh-noche-tertona-850kh2030-levaya.webp",
    "imageAlt": "Стоунвуд Скол камня блэк / Орех ноче тертона 850х2030 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Стоунвуд 850x2030 в Краснодаре по доступной цене 57&nbsp;610 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Стоунвуд",
      "Скол",
      "камня",
      "блэк",
      "Орех",
      "ноче",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "стоунвуд скол камня блэк / орех ноче тертона 850х2030 левая входные двери стоунвуд скол камня блэк орех ноче входные вх входная"
  },
  {
    "id": "tc-vh-praym-antik-mednyy-kedr-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/praym-antik-mednyy-kedr-860kh2050-levaya/",
    "title": "Прайм Антик медный / Кедр 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Прайм",
    "priceRetail": 22810,
    "imageSrc": "/catalog-real/tc-vh-praym-antik-mednyy-kedr-860kh2050-levaya.webp",
    "imageAlt": "Прайм Антик медный / Кедр 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Прайм 860x2050 в Краснодаре по доступной цене 22&nbsp;810 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Прайм",
      "Антик",
      "медный",
      "Кедр",
      "860х2050",
      "левая",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "прайм антик медный / кедр 860х2050 левая входные двери прайм антик медный кедр 860х2050 левая входные вх входная"
  },
  {
    "id": "tc-vh-praym-bukle-grafit-beloe-derevo-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/praym-bukle-grafit-beloe-derevo-860kh2050-levaya/",
    "title": "Прайм Букле графит / Белое дерево 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Прайм",
    "priceRetail": 22810,
    "imageSrc": "/catalog-real/tc-vh-praym-bukle-grafit-beloe-derevo-860kh2050-levaya.webp",
    "imageAlt": "Прайм Букле графит / Белое дерево 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Прайм 860x2050 в Краснодаре по доступной цене 22&nbsp;810 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Прайм",
      "Букле",
      "графит",
      "Белое",
      "дерево",
      "860х2050",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "прайм букле графит / белое дерево 860х2050 левая входные двери прайм букле графит белое дерево 860х2050 входные вх входная"
  },
  {
    "id": "tc-vh-marmoris-toros-grafit-belyy-mat-850kh2030-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/marmoris-toros-grafit-belyy-mat-850kh2030-levaya/",
    "title": "Марморис Торос графит / Белый мат 850х2030 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Марморис",
    "priceRetail": 59610,
    "imageSrc": "/catalog-real/tc-vh-marmoris-toros-grafit-belyy-mat-850kh2030-levaya.webp",
    "imageAlt": "Марморис Торос графит / Белый мат 850х2030 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Марморис 850x2030 в Краснодаре по доступной цене 59&nbsp;610 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Марморис",
      "Торос",
      "графит",
      "Белый",
      "мат",
      "850х2030",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "марморис торос графит / белый мат 850х2030 левая входные двери марморис торос графит белый мат 850х2030 входные вх входная"
  },
  {
    "id": "tc-vh-nuar-kvarts-chernyy-belyy-mat-850kh2030-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/nuar-kvarts-chernyy-belyy-mat-850kh2030-levaya/",
    "title": "Нуар Кварц черный / Белый мат 850х2030 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Нуар",
    "priceRetail": 43110,
    "imageSrc": "/catalog-real/tc-vh-nuar-kvarts-chernyy-belyy-mat-850kh2030-levaya.webp",
    "imageAlt": "Нуар Кварц черный / Белый мат 850х2030 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Нуар 850x2030 в Краснодаре по доступной цене 43&nbsp;110 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Нуар",
      "Кварц",
      "черный",
      "Белый",
      "мат",
      "850х2030",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "нуар кварц черный / белый мат 850х2030 левая входные двери нуар кварц черный белый мат 850х2030 входные вх входная"
  },
  {
    "id": "tc-vh-stroysib-1-venge-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/stroysib-1-venge-860kh2050-levaya/",
    "title": "Стройсиб 1 Венге 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Стройсиб 1",
    "priceRetail": 13110,
    "imageSrc": "/catalog-real/tc-vh-stroysib-1-venge-860kh2050-levaya.webp",
    "imageAlt": "Стройсиб 1 Венге 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Стройсиб-1 860x2050 в Краснодаре по доступной цене 13&nbsp;110 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Стройсиб",
      "Венге",
      "860х2050",
      "левая",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "стройсиб 1 венге 860х2050 левая входные двери стройсиб венге 860х2050 левая входные вх входная"
  },
  {
    "id": "tc-vh-avrora-morenaya-bereza-860-2050-l",
    "sourceUrl": "https://tandoor.ru/catalog/product/avrora-morenaya-bereza-860-2050-l/",
    "title": "Аврора Мореная Береза (860*2050) L",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Аврора",
    "priceRetail": 21910,
    "imageSrc": "/catalog-real/tc-vh-avrora-morenaya-bereza-860-2050-l.webp",
    "imageAlt": "Аврора Мореная Береза (860*2050) L",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Аврора 860x2050 в Краснодаре по доступной цене 21&nbsp;910 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Аврора",
      "Мореная",
      "Береза",
      "(860*2050)",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "аврора мореная береза (860*2050) l входные двери аврора мореная береза (860*2050) входные вх входная"
  },
  {
    "id": "tc-vh-avrora-venge-860-2050-l",
    "sourceUrl": "https://tandoor.ru/catalog/product/avrora-venge-860-2050-l/",
    "title": "Аврора Венге (860*2050) L",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Аврора",
    "priceRetail": 21910,
    "imageSrc": "/catalog-real/tc-vh-avrora-venge-860-2050-l.webp",
    "imageAlt": "Аврора Венге (860*2050) L",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Аврора 860x2050 в Краснодаре по доступной цене 21&nbsp;910 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Аврора",
      "Венге",
      "(860*2050)",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "аврора венге (860*2050) l входные двери аврора венге (860*2050) входные вх входная"
  },
  {
    "id": "tc-vh-stroysib-1-dub-belennyy-860kh2050-levaya",
    "sourceUrl": "https://tandoor.ru/catalog/product/stroysib-1-dub-belennyy-860kh2050-levaya/",
    "title": "Стройсиб 1 Дуб беленный 860х2050 левая",
    "category": "entrance",
    "categoryLabel": "Входные двери",
    "collection": "Стройсиб 1",
    "priceRetail": 13110,
    "imageSrc": "/catalog-real/tc-vh-stroysib-1-dub-belennyy-860kh2050-levaya.webp",
    "imageAlt": "Стройсиб 1 Дуб беленный 860х2050 левая",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить входную дверь Стройсиб-1 860x2050 в Краснодаре по доступной цене 13&nbsp;110 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Стройсиб",
      "Дуб",
      "беленный",
      "860х2050",
      "левая",
      "входные",
      "ВХ",
      "входная"
    ],
    "searchText": "стройсиб 1 дуб беленный 860х2050 левая входные двери стройсиб дуб беленный 860х2050 левая входные вх входная"
  },
  {
    "id": "tc-mk-new-siti-2-emal-7044-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/new-siti-2-emal-7044-dg-2000-800/",
    "title": "NEW Сити-2 эмаль 7044 ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "NEW",
    "priceRetail": 10530,
    "imageSrc": "/catalog-real/tc-mk-new-siti-2-emal-7044-dg-2000-800.webp",
    "imageAlt": "NEW Сити-2 эмаль 7044 ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери NEW Сити-2 2000х800 в Краснодаре по доступной цене 10&nbsp;530 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "NEW",
      "Сити-2",
      "эмаль",
      "7044",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "new сити-2 эмаль 7044 дг 2000*800 межкомнатные двери new сити-2 эмаль 7044 2000*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-shtorm-2-emal-belaya-dg-2100-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/shtorm-2-emal-belaya-dg-2100-800/",
    "title": "Шторм-2 эмаль белая ДГ 2100*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "Шторм-2",
    "priceRetail": 22200,
    "imageSrc": "/catalog-real/tc-mk-shtorm-2-emal-belaya-dg-2100-800.webp",
    "imageAlt": "Шторм-2 эмаль белая ДГ 2100*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери Шторм 2 (2100 мм) 2100х800 в Краснодаре по доступной цене 22&nbsp;200 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Шторм-2",
      "эмаль",
      "белая",
      "2100*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "шторм-2 эмаль белая дг 2100*800 межкомнатные двери шторм-2 эмаль белая 2100*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-maestro-2-ral-9010-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/maestro-2-ral-9010-dg-2000-800/",
    "title": "Маэстро-2 RAL 9010 ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "Маэстро-2",
    "priceRetail": 19440,
    "imageSrc": "/catalog-real/tc-mk-maestro-2-ral-9010-dg-2000-800.webp",
    "imageAlt": "Маэстро-2 RAL 9010 ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери Маэстро-2 2000х800 в Краснодаре по доступной цене 19&nbsp;440 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Маэстро-2",
      "RAL",
      "9010",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "маэстро-2 ral 9010 дг 2000*800 межкомнатные двери маэстро-2 ral 9010 2000*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-maestro-2-ral-9010-dg-2100-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/maestro-2-ral-9010-dg-2100-800/",
    "title": "Маэстро-2 RAL 9010 ДГ 2100*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "Маэстро-2",
    "priceRetail": 22200,
    "imageSrc": "/catalog-real/tc-mk-maestro-2-ral-9010-dg-2100-800.webp",
    "imageAlt": "Маэстро-2 RAL 9010 ДГ 2100*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери Маэстро 2 (2100 мм) 2100х800 в Краснодаре по доступной цене 22&nbsp;200 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Маэстро-2",
      "RAL",
      "9010",
      "2100*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "маэстро-2 ral 9010 дг 2100*800 межкомнатные двери маэстро-2 ral 9010 2100*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-m-24-1-emal-belaya-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/m-24-1-emal-belaya-dg-2000-800/",
    "title": "М-24/1 Эмаль белая ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "М-24/1",
    "priceRetail": 9890,
    "imageSrc": "/catalog-real/tc-mk-m-24-1-emal-belaya-dg-2000-800.webp",
    "imageAlt": "М-24/1 Эмаль белая ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери М-24/1 2000х800 в Краснодаре по доступной цене 9&nbsp;890 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "М-24",
      "Эмаль",
      "белая",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная",
      "эмаль"
    ],
    "searchText": "м-24/1 эмаль белая дг 2000*800 межкомнатные двери м-24 эмаль белая 2000*800 межкомнатные мк межкомнатная эмаль"
  },
  {
    "id": "tc-mk-m-25-emal-belaya-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/m-25-emal-belaya-dg-2000-800/",
    "title": "М-25 Эмаль белая ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "М-25",
    "priceRetail": 9890,
    "imageSrc": "/catalog-real/tc-mk-m-25-emal-belaya-dg-2000-800.webp",
    "imageAlt": "М-25 Эмаль белая ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери М-25 2000х800 в Краснодаре по доступной цене 9&nbsp;890 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "М-25",
      "Эмаль",
      "белая",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная",
      "эмаль"
    ],
    "searchText": "м-25 эмаль белая дг 2000*800 межкомнатные двери м-25 эмаль белая 2000*800 межкомнатные мк межкомнатная эмаль"
  },
  {
    "id": "tc-mk-benatti-1-0-belyy-zhemchug-dg-2100-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/benatti-1-0-belyy-zhemchug-dg-2100-800/",
    "title": "Бенатти 1.0 Белый жемчуг ДГ 2100*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "Бенатти 1.0",
    "priceRetail": 27860,
    "imageSrc": "/catalog-real/tc-mk-benatti-1-0-belyy-zhemchug-dg-2100-800.webp",
    "imageAlt": "Бенатти 1.0 Белый жемчуг ДГ 2100*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери Бенатти 1.0 (2100мм) 2100*800 в Краснодаре по доступной цене 27&nbsp;860 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Бенатти",
      "1.0",
      "Белый",
      "жемчуг",
      "2100*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "бенатти 1.0 белый жемчуг дг 2100*800 межкомнатные двери бенатти 1.0 белый жемчуг 2100*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-m-36-emal-belaya-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/m-36-emal-belaya-dg-2000-800/",
    "title": "М-36 эмаль белая ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "М-36",
    "priceRetail": 9890,
    "imageSrc": "/catalog-real/tc-mk-m-36-emal-belaya-dg-2000-800.webp",
    "imageAlt": "М-36 эмаль белая ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери М-36 2000х800 в Краснодаре по доступной цене 9&nbsp;890 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "М-36",
      "эмаль",
      "белая",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "м-36 эмаль белая дг 2000*800 межкомнатные двери м-36 эмаль белая 2000*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-new-siti-1-emal-belaya-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/new-siti-1-emal-belaya-dg-2000-800/",
    "title": "NEW Сити-1 Эмаль белая ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "NEW",
    "priceRetail": 9890,
    "imageSrc": "/catalog-real/tc-mk-new-siti-1-emal-belaya-dg-2000-800.webp",
    "imageAlt": "NEW Сити-1 Эмаль белая ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери NEW Сити-1 2000х800 в Краснодаре по доступной цене 9&nbsp;890 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "NEW",
      "Сити-1",
      "Эмаль",
      "белая",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная",
      "эмаль"
    ],
    "searchText": "new сити-1 эмаль белая дг 2000*800 межкомнатные двери new сити-1 эмаль белая 2000*800 межкомнатные мк межкомнатная эмаль"
  },
  {
    "id": "tc-mk-shtorm-2-emal-belaya-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/shtorm-2-emal-belaya-dg-2000-800/",
    "title": "Шторм-2 эмаль белая ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "Шторм-2",
    "priceRetail": 19440,
    "imageSrc": "/catalog-real/tc-mk-shtorm-2-emal-belaya-dg-2000-800.webp",
    "imageAlt": "Шторм-2 эмаль белая ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери Шторм-2 2000х800 в Краснодаре по доступной цене 19&nbsp;440 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Шторм-2",
      "эмаль",
      "белая",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "шторм-2 эмаль белая дг 2000*800 межкомнатные двери шторм-2 эмаль белая 2000*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-new-vektor-emal-belaya-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/new-vektor-emal-belaya-dg-2000-800/",
    "title": "NEW Вектор эмаль белая ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "NEW",
    "priceRetail": 9530,
    "imageSrc": "/catalog-real/tc-mk-new-vektor-emal-belaya-dg-2000-800.webp",
    "imageAlt": "NEW Вектор эмаль белая ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери NEW Вектор 2000х800 в Краснодаре по доступной цене 9&nbsp;530 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "NEW",
      "Вектор",
      "эмаль",
      "белая",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "new вектор эмаль белая дг 2000*800 межкомнатные двери new вектор эмаль белая 2000*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-new-vektor-ral-7035-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/new-vektor-ral-7035-dg-2000-800/",
    "title": "NEW Вектор RAL 7035 ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "NEW",
    "priceRetail": 9530,
    "imageSrc": "/catalog-real/tc-mk-new-vektor-ral-7035-dg-2000-800.webp",
    "imageAlt": "NEW Вектор RAL 7035 ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери NEW Вектор 2000х800 в Краснодаре по доступной цене 9&nbsp;530 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "NEW",
      "Вектор",
      "RAL",
      "7035",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "new вектор ral 7035 дг 2000*800 межкомнатные двери new вектор ral 7035 2000*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-new-kantata-emal-belaya-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/new-kantata-emal-belaya-dg-2000-800/",
    "title": "NEW Кантата эмаль белая ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "NEW",
    "priceRetail": 10020,
    "imageSrc": "/catalog-real/tc-mk-new-kantata-emal-belaya-dg-2000-800.webp",
    "imageAlt": "NEW Кантата эмаль белая ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери NEW Кантата 2000х800 в Краснодаре по доступной цене 10&nbsp;020 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "NEW",
      "Кантата",
      "эмаль",
      "белая",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "new кантата эмаль белая дг 2000*800 межкомнатные двери new кантата эмаль белая 2000*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-new-kantata-emal-belaya-dg-2100-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/new-kantata-emal-belaya-dg-2100-800/",
    "title": "NEW Кантата эмаль белая ДГ 2100*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "NEW",
    "priceRetail": 10950,
    "imageSrc": "/catalog-real/tc-mk-new-kantata-emal-belaya-dg-2100-800.webp",
    "imageAlt": "NEW Кантата эмаль белая ДГ 2100*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери NEW Кантата (2100мм) 2100х800 в Краснодаре по доступной цене 10&nbsp;950 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "NEW",
      "Кантата",
      "эмаль",
      "белая",
      "2100*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "new кантата эмаль белая дг 2100*800 межкомнатные двери new кантата эмаль белая 2100*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-new-kantata-emal-belaya-dg-2200-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/new-kantata-emal-belaya-dg-2200-800/",
    "title": "NEW Кантата эмаль белая ДГ 2200*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "NEW",
    "priceRetail": 11420,
    "imageSrc": "/catalog-real/tc-mk-new-kantata-emal-belaya-dg-2200-800.webp",
    "imageAlt": "NEW Кантата эмаль белая ДГ 2200*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери NEW Кантата (2200 мм) 2200х800 в Краснодаре по доступной цене 11&nbsp;420 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "NEW",
      "Кантата",
      "эмаль",
      "белая",
      "2200*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "new кантата эмаль белая дг 2200*800 межкомнатные двери new кантата эмаль белая 2200*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-new-kantata-emal-seraya-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/new-kantata-emal-seraya-dg-2000-800/",
    "title": "NEW Кантата эмаль серая ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "NEW",
    "priceRetail": 10020,
    "imageSrc": "/catalog-real/tc-mk-new-kantata-emal-seraya-dg-2000-800.webp",
    "imageAlt": "NEW Кантата эмаль серая ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери NEW Кантата 2000х800 в Краснодаре по доступной цене 10&nbsp;020 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "NEW",
      "Кантата",
      "эмаль",
      "серая",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "new кантата эмаль серая дг 2000*800 межкомнатные двери new кантата эмаль серая 2000*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-sirius-2-ral-9010-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/sirius-2-ral-9010-dg-2000-800/",
    "title": "Сириус-2 RAL 9010 ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "Сириус-2",
    "priceRetail": 22500,
    "imageSrc": "/catalog-real/tc-mk-sirius-2-ral-9010-dg-2000-800.webp",
    "imageAlt": "Сириус-2 RAL 9010 ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери Сириус-2 2000х800 в Краснодаре по доступной цене 22&nbsp;500 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Сириус-2",
      "RAL",
      "9010",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "сириус-2 ral 9010 дг 2000*800 межкомнатные двери сириус-2 ral 9010 2000*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-sirius-2-ral-9010-dg-2100-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/sirius-2-ral-9010-dg-2100-800/",
    "title": "Сириус-2 RAL 9010 ДГ 2100*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "Сириус-2",
    "priceRetail": 25700,
    "imageSrc": "/catalog-real/tc-mk-sirius-2-ral-9010-dg-2100-800.webp",
    "imageAlt": "Сириус-2 RAL 9010 ДГ 2100*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери Сириус-2 (2100 мм) 2100х800 в Краснодаре по доступной цене 25&nbsp;700 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Сириус-2",
      "RAL",
      "9010",
      "2100*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "сириус-2 ral 9010 дг 2100*800 межкомнатные двери сириус-2 ral 9010 2100*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-benatti-1-0-belyy-zhemchug-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/benatti-1-0-belyy-zhemchug-dg-2000-800/",
    "title": "Бенатти 1.0 Белый жемчуг ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "Бенатти 1.0",
    "priceRetail": 26530,
    "imageSrc": "/catalog-real/tc-mk-benatti-1-0-belyy-zhemchug-dg-2000-800.webp",
    "imageAlt": "Бенатти 1.0 Белый жемчуг ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери Бенатти 1.0 2000х800 в Краснодаре по доступной цене 26&nbsp;530 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Бенатти",
      "1.0",
      "Белый",
      "жемчуг",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "бенатти 1.0 белый жемчуг дг 2000*800 межкомнатные двери бенатти 1.0 белый жемчуг 2000*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-bagira-5-5mm-emal-slon-kost-patina-zoloto-s8",
    "sourceUrl": "https://tandoor.ru/catalog/product/bagira-5-5mm-emal-slon-kost-patina-zoloto-s8/",
    "title": "Багира (5,5мм) (эмаль слон.кость патина золото) С8",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "Багира (5,5мм) (эмаль",
    "priceRetail": 26800,
    "imageSrc": "/catalog-real/tc-mk-bagira-5-5mm-emal-slon-kost-patina-zoloto-s8.webp",
    "imageAlt": "Багира (5,5мм) (эмаль слон.кость патина золото) С8",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери Багира 2000х800 в Краснодаре по доступной цене 26&nbsp;800 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Багира",
      "5мм)",
      "(эмаль",
      "слон.кость",
      "патина",
      "золото)",
      "межкомнатные",
      "МК",
      "межкомнатная",
      "эмаль"
    ],
    "searchText": "багира (5,5мм) (эмаль слон.кость патина золото) с8 межкомнатные двери багира 5мм) (эмаль слон.кость патина золото) межкомнатные мк межкомнатная эмаль"
  },
  {
    "id": "tc-mk-benatti-2-belyy-zhemchug-dg-2000-800",
    "sourceUrl": "https://tandoor.ru/catalog/product/benatti-2-belyy-zhemchug-dg-2000-800/",
    "title": "Бенатти 2 Белый жемчуг ДГ 2000*800",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "Бенатти 2",
    "priceRetail": 26530,
    "imageSrc": "/catalog-real/tc-mk-benatti-2-belyy-zhemchug-dg-2000-800.webp",
    "imageAlt": "Бенатти 2 Белый жемчуг ДГ 2000*800",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери Бенатти 2.0 2000х800 в Краснодаре по доступной цене 26&nbsp;530 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Бенатти",
      "Белый",
      "жемчуг",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "бенатти 2 белый жемчуг дг 2000*800 межкомнатные двери бенатти белый жемчуг 2000*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-mk-angliyskaya-reshetka-15-belyy-zhemchug-2000-800-dg",
    "sourceUrl": "https://tandoor.ru/catalog/product/angliyskaya-reshetka-15-belyy-zhemchug-2000-800-dg/",
    "title": "Английская решетка 15 белый жемчуг 2000*800 ДГ",
    "category": "interior",
    "categoryLabel": "Межкомнатные двери",
    "collection": "Английская",
    "priceRetail": 24680,
    "imageSrc": "/catalog-real/tc-mk-angliyskaya-reshetka-15-belyy-zhemchug-2000-800-dg.webp",
    "imageAlt": "Английская решетка 15 белый жемчуг 2000*800 ДГ",
    "shortDescription": "Интернет-магазин Tandoor.ru предлагает купить межкомнатные двери Английская решетка 15 2000х800 в Краснодаре по доступной цене 24&nbsp;680 &#8381; рублей. Качественное обслуживание. Доставка.",
    "tags": [
      "Английская",
      "решетка",
      "белый",
      "жемчуг",
      "2000*800",
      "межкомнатные",
      "МК",
      "межкомнатная"
    ],
    "searchText": "английская решетка 15 белый жемчуг 2000*800 дг межкомнатные двери английская решетка белый жемчуг 2000*800 межкомнатные мк межкомнатная"
  },
  {
    "id": "tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-m-cyl-black-chernyy",
    "sourceUrl": "https://tandoor.ru/catalog/product/zamok-pod-tsilindr-tandoor-tdlb-5085-m-cyl-black-chernyy/",
    "title": "Замок под цилиндр TANDOOR TDLB 5085-M CYL BLACK черный",
    "category": "hardware",
    "categoryLabel": "Фурнитура",
    "collection": "Замок",
    "priceRetail": 710,
    "imageSrc": "/catalog-real/tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-m-cyl-black-chernyy.webp",
    "imageAlt": "Замок под цилиндр TANDOOR TDLB 5085-M CYL BLACK черный",
    "shortDescription": "Замок под цилиндр TANDOOR TDLB 5085-M CYL BLACK черный по цене от 710 &#8381; рублей в интернет-магазине Tandoor в Краснодаре. Большой выбор качественных дверей и фурнитуры по выгодной цене. Быстрая доставка по России.",
    "tags": [
      "Замок",
      "под",
      "цилиндр",
      "TANDOOR",
      "TDLB",
      "5085-M",
      "фурнитура",
      "замок",
      "комплектующие"
    ],
    "searchText": "замок под цилиндр tandoor tdlb 5085-m cyl black черный фурнитура замок под цилиндр tandoor tdlb 5085-m фурнитура замок комплектующие"
  },
  {
    "id": "tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-m-cyl-cp-khrom",
    "sourceUrl": "https://tandoor.ru/catalog/product/zamok-pod-tsilindr-tandoor-tdlb-5085-m-cyl-cp-khrom/",
    "title": "Замок под цилиндр TANDOOR TDLB 5085-M CYL CP хром",
    "category": "hardware",
    "categoryLabel": "Фурнитура",
    "collection": "Замок",
    "priceRetail": 710,
    "imageSrc": "/catalog-real/tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-m-cyl-cp-khrom.webp",
    "imageAlt": "Замок под цилиндр TANDOOR TDLB 5085-M CYL CP хром",
    "shortDescription": "Замок под цилиндр TANDOOR TDLB 5085-M CYL CP Хром по цене от 710 &#8381; рублей в интернет-магазине Tandoor в Краснодаре. Большой выбор качественных дверей и фурнитуры по выгодной цене. Быстрая доставка по России.",
    "tags": [
      "Замок",
      "под",
      "цилиндр",
      "TANDOOR",
      "TDLB",
      "5085-M",
      "фурнитура",
      "замок",
      "комплектующие"
    ],
    "searchText": "замок под цилиндр tandoor tdlb 5085-m cyl cp хром фурнитура замок под цилиндр tandoor tdlb 5085-m фурнитура замок комплектующие"
  },
  {
    "id": "tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-m-cyl-sn-nikel",
    "sourceUrl": "https://tandoor.ru/catalog/product/zamok-pod-tsilindr-tandoor-tdlb-5085-m-cyl-sn-nikel/",
    "title": "Замок под цилиндр TANDOOR TDLB 5085-M CYL SN никель",
    "category": "hardware",
    "categoryLabel": "Фурнитура",
    "collection": "Замок",
    "priceRetail": 710,
    "imageSrc": "/catalog-real/tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-m-cyl-sn-nikel.webp",
    "imageAlt": "Замок под цилиндр TANDOOR TDLB 5085-M CYL SN никель",
    "shortDescription": "Замок под цилиндр TANDOOR TDLB 5085-M CYL SN никель по цене от 710 &#8381; рублей в интернет-магазине Tandoor в Краснодаре. Большой выбор качественных дверей и фурнитуры по выгодной цене. Быстрая доставка по России.",
    "tags": [
      "Замок",
      "под",
      "цилиндр",
      "TANDOOR",
      "TDLB",
      "5085-M",
      "фурнитура",
      "замок",
      "комплектующие"
    ],
    "searchText": "замок под цилиндр tandoor tdlb 5085-m cyl sn никель фурнитура замок под цилиндр tandoor tdlb 5085-m фурнитура замок комплектующие"
  },
  {
    "id": "tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-ab-bronza",
    "sourceUrl": "https://tandoor.ru/catalog/product/zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-ab-bronza/",
    "title": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic AB бронза",
    "category": "hardware",
    "categoryLabel": "Фурнитура",
    "collection": "Замок",
    "priceRetail": 660,
    "imageSrc": "/catalog-real/tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-ab-bronza.webp",
    "imageAlt": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic AB бронза",
    "shortDescription": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic AB бронза по цене от 660 &#8381; рублей в интернет-магазине Tandoor в Краснодаре. Большой выбор качественных дверей и фурнитуры по выгодной цене. Быстрая доставка по России.",
    "tags": [
      "Замок",
      "под",
      "цилиндр",
      "TANDOOR",
      "TDLB",
      "5085-P",
      "фурнитура",
      "замок",
      "комплектующие"
    ],
    "searchText": "замок под цилиндр tandoor tdlb 5085-p cyl plastic ab бронза фурнитура замок под цилиндр tandoor tdlb 5085-p фурнитура замок комплектующие"
  },
  {
    "id": "tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-black-chernyy",
    "sourceUrl": "https://tandoor.ru/catalog/product/zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-black-chernyy/",
    "title": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic BLACK черный",
    "category": "hardware",
    "categoryLabel": "Фурнитура",
    "collection": "Замок",
    "priceRetail": 660,
    "imageSrc": "/catalog-real/tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-black-chernyy.webp",
    "imageAlt": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic BLACK черный",
    "shortDescription": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic BLACK черный по цене от 660 &#8381; рублей в интернет-магазине Tandoor в Краснодаре. Большой выбор качественных дверей и фурнитуры по выгодной цене. Быстрая доставка по России.",
    "tags": [
      "Замок",
      "под",
      "цилиндр",
      "TANDOOR",
      "TDLB",
      "5085-P",
      "фурнитура",
      "замок",
      "комплектующие"
    ],
    "searchText": "замок под цилиндр tandoor tdlb 5085-p cyl plastic black черный фурнитура замок под цилиндр tandoor tdlb 5085-p фурнитура замок комплектующие"
  },
  {
    "id": "tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-cp-khrom",
    "sourceUrl": "https://tandoor.ru/catalog/product/zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-cp-khrom/",
    "title": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic CP хром",
    "category": "hardware",
    "categoryLabel": "Фурнитура",
    "collection": "Замок",
    "priceRetail": 660,
    "imageSrc": "/catalog-real/tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-cp-khrom.webp",
    "imageAlt": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic CP хром",
    "shortDescription": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic CP Хром по цене от 660 &#8381; рублей в интернет-магазине Tandoor в Краснодаре. Большой выбор качественных дверей и фурнитуры по выгодной цене. Быстрая доставка по России.",
    "tags": [
      "Замок",
      "под",
      "цилиндр",
      "TANDOOR",
      "TDLB",
      "5085-P",
      "фурнитура",
      "замок",
      "комплектующие"
    ],
    "searchText": "замок под цилиндр tandoor tdlb 5085-p cyl plastic cp хром фурнитура замок под цилиндр tandoor tdlb 5085-p фурнитура замок комплектующие"
  },
  {
    "id": "tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-grf-grafit",
    "sourceUrl": "https://tandoor.ru/catalog/product/zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-grf-grafit/",
    "title": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic GRF графит",
    "category": "hardware",
    "categoryLabel": "Фурнитура",
    "collection": "Замок",
    "priceRetail": 660,
    "imageSrc": "/catalog-real/tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-grf-grafit.webp",
    "imageAlt": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic GRF графит",
    "shortDescription": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic GRF графит по цене от 660 &#8381; рублей в интернет-магазине Tandoor в Краснодаре. Большой выбор качественных дверей и фурнитуры по выгодной цене. Быстрая доставка по России.",
    "tags": [
      "Замок",
      "под",
      "цилиндр",
      "TANDOOR",
      "TDLB",
      "5085-P",
      "фурнитура",
      "замок",
      "комплектующие"
    ],
    "searchText": "замок под цилиндр tandoor tdlb 5085-p cyl plastic grf графит фурнитура замок под цилиндр tandoor tdlb 5085-p фурнитура замок комплектующие"
  },
  {
    "id": "tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-sn-nikel",
    "sourceUrl": "https://tandoor.ru/catalog/product/zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-sn-nikel/",
    "title": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic SN никель",
    "category": "hardware",
    "categoryLabel": "Фурнитура",
    "collection": "Замок",
    "priceRetail": 660,
    "imageSrc": "/catalog-real/tc-hw-zamok-pod-tsilindr-tandoor-tdlb-5085-p-cyl-plastic-sn-nikel.webp",
    "imageAlt": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic SN никель",
    "shortDescription": "Замок под цилиндр TANDOOR TDLB 5085-P CYL plastic SN никель по цене от 660 &#8381; рублей в интернет-магазине Tandoor в Краснодаре. Большой выбор качественных дверей и фурнитуры по выгодной цене. Быстрая доставка по России.",
    "tags": [
      "Замок",
      "под",
      "цилиндр",
      "TANDOOR",
      "TDLB",
      "5085-P",
      "фурнитура",
      "замок",
      "комплектующие"
    ],
    "searchText": "замок под цилиндр tandoor tdlb 5085-p cyl plastic sn никель фурнитура замок под цилиндр tandoor tdlb 5085-p фурнитура замок комплектующие"
  },
  {
    "id": "tc-hw-zamok-santekhnicheskiy-tandoor-tdlb-5096-m-wc-ab-bronza",
    "sourceUrl": "https://tandoor.ru/catalog/product/zamok-santekhnicheskiy-tandoor-tdlb-5096-m-wc-ab-bronza/",
    "title": "Замок сантехнический TANDOOR TDLB 5096-M WC AB бронза",
    "category": "hardware",
    "categoryLabel": "Фурнитура",
    "collection": "Замок",
    "priceRetail": 710,
    "imageSrc": "/catalog-real/tc-hw-zamok-santekhnicheskiy-tandoor-tdlb-5096-m-wc-ab-bronza.webp",
    "imageAlt": "Замок сантехнический TANDOOR TDLB 5096-M WC AB бронза",
    "shortDescription": "Замок сантехнический TANDOOR TDLB 5096-M WC AB бронза по цене от 710 &#8381; рублей в интернет-магазине Tandoor в Краснодаре. Большой выбор качественных дверей и фурнитуры по выгодной цене. Быстрая доставка по России.",
    "tags": [
      "Замок",
      "сантехнический",
      "TANDOOR",
      "TDLB",
      "5096-M",
      "бронза",
      "фурнитура",
      "замок",
      "комплектующие"
    ],
    "searchText": "замок сантехнический tandoor tdlb 5096-m wc ab бронза фурнитура замок сантехнический tandoor tdlb 5096-m бронза фурнитура замок комплектующие"
  },
  {
    "id": "tc-hw-zamok-santekhnicheskiy-tandoor-tdlb-5096-m-wc-black-chernyy",
    "sourceUrl": "https://tandoor.ru/catalog/product/zamok-santekhnicheskiy-tandoor-tdlb-5096-m-wc-black-chernyy/",
    "title": "Замок сантехнический TANDOOR TDLB 5096-M WC BLACK черный",
    "category": "hardware",
    "categoryLabel": "Фурнитура",
    "collection": "Замок",
    "priceRetail": 710,
    "imageSrc": "/catalog-real/tc-hw-zamok-santekhnicheskiy-tandoor-tdlb-5096-m-wc-black-chernyy.webp",
    "imageAlt": "Замок сантехнический TANDOOR TDLB 5096-M WC BLACK черный",
    "shortDescription": "Замок сантехнический TANDOOR TDLB 5096-M WC BLACK черный по цене от 710 &#8381; рублей в интернет-магазине Tandoor в Краснодаре. Большой выбор качественных дверей и фурнитуры по выгодной цене. Быстрая доставка по России.",
    "tags": [
      "Замок",
      "сантехнический",
      "TANDOOR",
      "TDLB",
      "5096-M",
      "BLACK",
      "фурнитура",
      "замок",
      "комплектующие"
    ],
    "searchText": "замок сантехнический tandoor tdlb 5096-m wc black черный фурнитура замок сантехнический tandoor tdlb 5096-m black фурнитура замок комплектующие"
  },
  {
    "id": "tc-hw-zamok-santekhnicheskiy-tandoor-tdlb-5096-m-wc-cp-khrom",
    "sourceUrl": "https://tandoor.ru/catalog/product/zamok-santekhnicheskiy-tandoor-tdlb-5096-m-wc-cp-khrom/",
    "title": "Замок сантехнический TANDOOR TDLB 5096-M WC CP хром",
    "category": "hardware",
    "categoryLabel": "Фурнитура",
    "collection": "Замок",
    "priceRetail": 710,
    "imageSrc": "/catalog-real/tc-hw-zamok-santekhnicheskiy-tandoor-tdlb-5096-m-wc-cp-khrom.webp",
    "imageAlt": "Замок сантехнический TANDOOR TDLB 5096-M WC CP хром",
    "shortDescription": "Замок сантехнический TANDOOR TDLB 5096-M WC CP Хром по цене от 710 &#8381; рублей в интернет-магазине Tandoor в Краснодаре. Большой выбор качественных дверей и фурнитуры по выгодной цене. Быстрая доставка по России.",
    "tags": [
      "Замок",
      "сантехнический",
      "TANDOOR",
      "TDLB",
      "5096-M",
      "хром",
      "фурнитура",
      "замок",
      "комплектующие"
    ],
    "searchText": "замок сантехнический tandoor tdlb 5096-m wc cp хром фурнитура замок сантехнический tandoor tdlb 5096-m хром фурнитура замок комплектующие"
  },
  {
    "id": "tc-hw-zamok-santekhnicheskiy-tandoor-tdlb-5096-m-wc-grf-grafit",
    "sourceUrl": "https://tandoor.ru/catalog/product/zamok-santekhnicheskiy-tandoor-tdlb-5096-m-wc-grf-grafit/",
    "title": "Замок сантехнический TANDOOR TDLB 5096-M WC GRF графит",
    "category": "hardware",
    "categoryLabel": "Фурнитура",
    "collection": "Замок",
    "priceRetail": 710,
    "imageSrc": "/catalog-real/tc-hw-zamok-santekhnicheskiy-tandoor-tdlb-5096-m-wc-grf-grafit.webp",
    "imageAlt": "Замок сантехнический TANDOOR TDLB 5096-M WC GRF графит",
    "shortDescription": "Замок сантехнический TANDOOR TDLB 5096-M WC GRF графит по цене от 710 &#8381; рублей в интернет-магазине Tandoor в Краснодаре. Большой выбор качественных дверей и фурнитуры по выгодной цене. Быстрая доставка по России.",
    "tags": [
      "Замок",
      "сантехнический",
      "TANDOOR",
      "TDLB",
      "5096-M",
      "GRF",
      "фурнитура",
      "замок",
      "комплектующие"
    ],
    "searchText": "замок сантехнический tandoor tdlb 5096-m wc grf графит фурнитура замок сантехнический tandoor tdlb 5096-m grf фурнитура замок комплектующие"
  }
];
