import type { DealerRow, DealerTradePoint } from "./dealer-base-mock-data.js";

export type TradePointDisplayNameContext = {
  name?: string | null;
  city?: string | null;
  address?: string | null;
  contactPhone?: string | null;
  dealerName?: string | null;
  dealerId?: string | null;
  tradePointId?: string | null;
  releaseCode?: string | null;
};

const STREET_HINT =
  /^(ул\.|улица|пр\.|просп\.|проспект|пер\.|переулок|бул\.|бульвар|ш\.|шоссе|наб\.|набережная|пл\.|площадь|мкр\.|микрорайон|кв\.|квартал|туп\.|тупик|ал\.|аллея|проезд|линия|тер\.|территория)/i;

function cleanPart(value?: string | null): string {
  return (value ?? "").replace(/\s+/g, " ").trim();
}

function normalizeCityToken(value?: string | null): string {
  return cleanPart(value)
    .replace(/\s+г\.?$/i, "")
    .replace(/^г\.?\s+/i, "")
    .toLowerCase();
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Прежняя автогенерация имени — не считается ручным override. */
export function isLegacyAutoGeneratedTradePointName(name: string, city?: string | null): boolean {
  const t = cleanPart(name);
  if (!t) return false;
  if (/^основная торговая точка$/i.test(t)) return true;
  if (/^точка \(синхронизирована\)$/i.test(t)) return true;
  if (/^торговая точка\s+\d+$/i.test(t)) return true;
  if (/^торговая точка\s*[·•]\s*/i.test(t)) return true;
  if (/^торговая точка$/i.test(t)) return true;
  const cityNorm = normalizeCityToken(city);
  if (cityNorm) {
    const cityPattern = new RegExp(`^торговая точка\\s*[·•]?\\s*${escapeRegExp(cityNorm)}$`, "i");
    if (cityPattern.test(t.toLowerCase())) return true;
  }
  return false;
}

/** Ручное имя: осмысленное и не из старого шаблона «Торговая точка · …». */
export function isManualTradePointName(name?: string | null, city?: string | null): boolean {
  const t = cleanPart(name);
  if (!t || t === ".") return false;
  return !isLegacyAutoGeneratedTradePointName(t, city);
}

function isHousePart(part: string): boolean {
  return /^дом(?:\s|$)/i.test(part) || /^д\.?\s/i.test(part) || /^№\s*\S/.test(part);
}

function formatHousePart(part: string): string {
  return part
    .replace(/^дом\s+/i, "")
    .replace(/^д\.?\s*/i, "")
    .replace(/\s+/g, " ")
    .trim();
}

function hasInlineHouseNumber(part: string): boolean {
  return /\d/.test(part) && !isHousePart(part);
}

/** Компактная «улица + дом» из полного адреса (без индекса, региона и города). */
export function extractStreetAndHouseFromAddress(
  address?: string | null,
  city?: string | null,
): string | null {
  const raw = cleanPart(address);
  if (!raw) return null;

  let parts = raw
    .split(/[,;]+/)
    .map(cleanPart)
    .filter(Boolean);
  if (!parts.length) return null;

  if (/^\d{6}$/.test(parts[0]!)) parts = parts.slice(1);

  const cityNorm = normalizeCityToken(city);
  const filtered = parts.filter((part) => {
    const partNorm = normalizeCityToken(part);
    if (cityNorm && partNorm === cityNorm) return false;
    if (/\b(край|область|обл\.|республика|респ\.|ао|округ)\b/i.test(part)) return false;
    if (/\sг\.?$/i.test(part)) {
      const withoutCitySuffix = part.replace(/\s*г\.?\s*$/i, "").trim();
      if (cityNorm && normalizeCityToken(withoutCitySuffix) === cityNorm) return false;
    }
    return true;
  });
  if (!filtered.length) return null;

  for (let i = 0; i < filtered.length; i++) {
    const part = filtered[i]!;
    const next = filtered[i + 1];
    if (STREET_HINT.test(part) || hasInlineHouseNumber(part)) {
      if (next && isHousePart(next)) return `${part}, ${formatHousePart(next)}`;
      return part;
    }
    if (isHousePart(part)) {
      const prev = i > 0 ? filtered[i - 1] : null;
      if (prev && !STREET_HINT.test(prev) && !isHousePart(prev) && !hasInlineHouseNumber(prev)) {
        return `${prev}, ${formatHousePart(part)}`;
      }
      return formatHousePart(part);
    }
  }

  const last = filtered[filtered.length - 1];
  return last && last.length > 1 ? last : null;
}

function formatDealerIdSuffix(dealerId?: string | null): string | null {
  const id = cleanPart(dealerId);
  if (!id) return null;
  const short = id.replace(/^client-/i, "");
  return `#${short}`;
}

function formatClientSuffix(dealerName?: string | null, dealerId?: string | null): string {
  const name = cleanPart(dealerName);
  const idSuffix = formatDealerIdSuffix(dealerId);
  if (name && idSuffix) return `(${name}, ${idSuffix})`;
  if (name) return `(${name})`;
  if (idSuffix) return `(${idSuffix})`;
  return "";
}

/** Автоназвание: «Город, улица — тел. (Клиент, #id)». */
export function computeTradePointAutoDisplayName(ctx: TradePointDisplayNameContext): string | null {
  const city = cleanPart(ctx.city);
  const street = extractStreetAndHouseFromAddress(ctx.address, city);
  const phone = cleanPart(ctx.contactPhone);
  const client = formatClientSuffix(ctx.dealerName, ctx.dealerId);

  const location = [city, street].filter(Boolean).join(", ");
  if (!location && !phone && !client) return null;

  let result = location;
  if (phone) result = result ? `${result} — ${phone}` : phone;
  if (client) result = result ? `${result} ${client}` : client;
  return result || null;
}

export function displayNameContextFromDealerPoint(
  dealer: Pick<DealerRow, "name" | "id">,
  point: Pick<DealerTradePoint, "name" | "city" | "address" | "contactPhone" | "releaseCode" | "id">,
): TradePointDisplayNameContext {
  return {
    name: point.name,
    city: point.city,
    address: point.address,
    contactPhone: point.contactPhone,
    dealerName: dealer.name,
    dealerId: dealer.id,
    tradePointId: point.id,
    releaseCode: point.releaseCode,
  };
}

/** Отображаемое имя ТТ: ручное override или автоназвание по адресу. */
export function computeTradePointDisplayName(ctx: TradePointDisplayNameContext): string {
  if (isManualTradePointName(ctx.name, ctx.city)) return cleanPart(ctx.name);
  const auto = computeTradePointAutoDisplayName(ctx);
  if (auto) return auto;
  const code = cleanPart(ctx.releaseCode);
  if (code) return code;
  const id = cleanPart(ctx.tradePointId);
  if (id) return id;
  return "Торговая точка";
}

export function resolveTradePointDisplayName(
  dealer: Pick<DealerRow, "name" | "id">,
  point: Pick<DealerTradePoint, "name" | "city" | "address" | "contactPhone" | "releaseCode" | "id">,
): string {
  return computeTradePointDisplayName(displayNameContextFromDealerPoint(dealer, point));
}

/** Значение для поля редактирования «Название» (пусто = автоназвание). */
export function tradePointManualNameForEdit(name?: string | null, city?: string | null): string {
  return isManualTradePointName(name, city) ? cleanPart(name) : "";
}

/** Осмысленное имя ТТ или null (отсекает пустые и заглушки вроде "."). */
export function meaningfulTradePointName(name?: string): string | null {
  const t = cleanPart(name);
  if (!t || t === ".") return null;
  return t;
}

export function tradePointDisplayLabel(
  point: Pick<DealerTradePoint, "name" | "releaseCode" | "id" | "city" | "address" | "contactPhone">,
  dealer?: Pick<DealerRow, "name" | "id">,
): string {
  if (dealer) {
    return resolveTradePointDisplayName(dealer, point);
  }
  return computeTradePointDisplayName({
    name: point.name,
    city: point.city,
    address: point.address,
    contactPhone: point.contactPhone,
    tradePointId: point.id,
    releaseCode: point.releaseCode,
  });
}

/** Строка «клиент · ТТ: …» для компактной шапки fullscreen-ввода. */
export function fullscreenCounterpartyLine(
  dealer: Pick<DealerRow, "name" | "id">,
  point: Pick<DealerTradePoint, "name" | "releaseCode" | "id" | "city" | "address" | "contactPhone">,
): string {
  const dealerName = dealer.name?.trim() || "Клиент";
  const tp = tradePointDisplayLabel(point, dealer);
  return `${dealerName} · ТТ: ${tp}`;
}
